# Generated by Django 5.0.3 on 2024-03-17 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_no', models.IntegerField()),
                ('Staff_Name', models.CharField(max_length=100)),
                ('Experiance', models.ImageField(upload_to='')),
                ('Department', models.CharField(choices=[('Mathematics', 'Math'), ('Computer Science', 'Cs'), ('Physics', 'Phy')], default='Unknown', max_length=30)),
                ('Extra_Info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('morning_present', models.BooleanField(default=False)),
                ('afternoon_present', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.staff')),
            ],
        ),
    ]
