# Generated by Django 5.0.3 on 2024-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Staff_Photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='Department',
            field=models.CharField(choices=[('Mathematics', 'Math'), ('Computer Science', 'Cs'), ('Physics', 'Phy')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Experiance',
            field=models.IntegerField(),
        ),
    ]
