# Generated by Django 5.0.3 on 2024-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_staff_staff_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
