# Generated by Django 5.0.3 on 2024-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_staff_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
