# Generated by Django 5.0.3 on 2024-03-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_staff_sr_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'attendances'},
        ),
    ]
