# Generated by Django 5.0.3 on 2024-03-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AddField(
            model_name='attendance',
            name='Sr_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.staff', to_field='Sr_no'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Sr_no',
            field=models.IntegerField(unique=True),
        ),
    ]
