# Generated by Django 5.0.3 on 2024-03-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_attendance_options_attendance_sr_no_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Sr_no',
        ),
    ]
