# Generated by Django 5.0.3 on 2024-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_examdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='Date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='Duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
